//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevexLambda1 {
    
    public partial class XtraReport1 : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "devexReports.XtraReport1.repx");

            // Controls
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.GroupHeader1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.GroupHeaderBand>("GroupHeader1");
            this.GroupFooter1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.GroupFooterBand>("GroupFooter1");
            this.detailTable = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("detailTable");
            this.detailTableRow = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("detailTableRow");
            this.quantity = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("quantity");
            this.productName = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("productName");
            this.unitPrice = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("unitPrice");
            this.lineTotal = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("lineTotal");
            this.vendorContactsTable = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("vendorContactsTable");
            this.xrLine1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLine>("xrLine1");
            this.vendorContactsRow = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("vendorContactsRow");
            this.vendorWebsite = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("vendorWebsite");
            this.vendorEmail = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("vendorEmail");
            this.vendorPhone = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("vendorPhone");
            this.invoiceDate = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("invoiceDate");
            this.vendorLogo = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPictureBox>("vendorLogo");
            this.vendorTable = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("vendorTable");
            this.customerTable = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("customerTable");
            this.vendorNameRow = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("vendorNameRow");
            this.vendorAddressRow = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("vendorAddressRow");
            this.vendorCityRow = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("vendorCityRow");
            this.vendorCountryRow = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("vendorCountryRow");
            this.vendorName = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("vendorName");
            this.vendorAddress = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("vendorAddress");
            this.vendorCity = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("vendorCity");
            this.vendorCountry = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("vendorCountry");
            this.customerNameRow = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("customerNameRow");
            this.customerAddressRow = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("customerAddressRow");
            this.customerCityRow = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("customerCityRow");
            this.customerCountryRow = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("customerCountryRow");
            this.customerName = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("customerName");
            this.customerAddress = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("customerAddress");
            this.customerCity = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("customerCity");
            this.customerCountry = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("customerCountry");
            this.SubBand1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.SubBand>("SubBand1");
            this.headerTable = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("headerTable");
            this.invoiceNumberTable = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("invoiceNumberTable");
            this.invoiceLabel = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("invoiceLabel");
            this.headerTableRow = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("headerTableRow");
            this.quantityCaption = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("quantityCaption");
            this.productNameCaption = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("productNameCaption");
            this.unitPriceCaption = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("unitPriceCaption");
            this.lineTotalCaption = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("lineTotalCaption");
            this.invoiceNumberCaptionRow = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("invoiceNumberCaptionRow");
            this.invoiceNumberRow = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("invoiceNumberRow");
            this.invoiceNumberCaption = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("invoiceNumberCaption");
            this.invoiceNumber = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("invoiceNumber");
            this.totalTable = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTable>("totalTable");
            this.subtotalRow = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("subtotalRow");
            this.discountRow = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("discountRow");
            this.taxRow = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("taxRow");
            this.totalRow = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableRow>("totalRow");
            this.subtotalCaption = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("subtotalCaption");
            this.subtotal = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("subtotal");
            this.discountCaption = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("discountCaption");
            this.discount = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("discount");
            this.taxCaption = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("taxCaption");
            this.tax = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("tax");
            this.totalCaption = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("totalCaption");
            this.total = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRTableCell>("total");

            // Parameters
            this.InvoiceDateParameter = reportInitializer.GetParameter("InvoiceDateParameter");
            this.QuantityParameter = reportInitializer.GetParameter("QuantityParameter");
            this.UnitPriceParameter = reportInitializer.GetParameter("UnitPriceParameter");
            this.DiscountParameter = reportInitializer.GetParameter("DiscountParameter");
            this.TaxParameter = reportInitializer.GetParameter("TaxParameter");

            // Calculated Fields
            this.LineTotalCalcField = reportInitializer.GetCalculatedField("LineTotalCalcField");
            this.SubtotalCalcField = reportInitializer.GetCalculatedField("SubtotalCalcField");
            this.TotalCalcField = reportInitializer.GetCalculatedField("TotalCalcField");

            // Styles
            this.baseControlStyle = reportInitializer.GetStyle("baseControlStyle");
        }
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.GroupHeaderBand GroupHeader1;
        private DevExpress.XtraReports.UI.GroupFooterBand GroupFooter1;
        private DevExpress.XtraReports.UI.XRTable detailTable;
        private DevExpress.XtraReports.UI.XRTableRow detailTableRow;
        private DevExpress.XtraReports.UI.XRTableCell quantity;
        private DevExpress.XtraReports.UI.XRTableCell productName;
        private DevExpress.XtraReports.UI.XRTableCell unitPrice;
        private DevExpress.XtraReports.UI.XRTableCell lineTotal;
        private DevExpress.XtraReports.UI.XRTable vendorContactsTable;
        private DevExpress.XtraReports.UI.XRLine xrLine1;
        private DevExpress.XtraReports.UI.XRTableRow vendorContactsRow;
        private DevExpress.XtraReports.UI.XRTableCell vendorWebsite;
        private DevExpress.XtraReports.UI.XRTableCell vendorEmail;
        private DevExpress.XtraReports.UI.XRTableCell vendorPhone;
        private DevExpress.XtraReports.UI.XRLabel invoiceDate;
        private DevExpress.XtraReports.UI.XRPictureBox vendorLogo;
        private DevExpress.XtraReports.UI.XRTable vendorTable;
        private DevExpress.XtraReports.UI.XRTable customerTable;
        private DevExpress.XtraReports.UI.XRTableRow vendorNameRow;
        private DevExpress.XtraReports.UI.XRTableRow vendorAddressRow;
        private DevExpress.XtraReports.UI.XRTableRow vendorCityRow;
        private DevExpress.XtraReports.UI.XRTableRow vendorCountryRow;
        private DevExpress.XtraReports.UI.XRTableCell vendorName;
        private DevExpress.XtraReports.UI.XRTableCell vendorAddress;
        private DevExpress.XtraReports.UI.XRTableCell vendorCity;
        private DevExpress.XtraReports.UI.XRTableCell vendorCountry;
        private DevExpress.XtraReports.UI.XRTableRow customerNameRow;
        private DevExpress.XtraReports.UI.XRTableRow customerAddressRow;
        private DevExpress.XtraReports.UI.XRTableRow customerCityRow;
        private DevExpress.XtraReports.UI.XRTableRow customerCountryRow;
        private DevExpress.XtraReports.UI.XRTableCell customerName;
        private DevExpress.XtraReports.UI.XRTableCell customerAddress;
        private DevExpress.XtraReports.UI.XRTableCell customerCity;
        private DevExpress.XtraReports.UI.XRTableCell customerCountry;
        private DevExpress.XtraReports.UI.SubBand SubBand1;
        private DevExpress.XtraReports.UI.XRTable headerTable;
        private DevExpress.XtraReports.UI.XRTable invoiceNumberTable;
        private DevExpress.XtraReports.UI.XRLabel invoiceLabel;
        private DevExpress.XtraReports.UI.XRTableRow headerTableRow;
        private DevExpress.XtraReports.UI.XRTableCell quantityCaption;
        private DevExpress.XtraReports.UI.XRTableCell productNameCaption;
        private DevExpress.XtraReports.UI.XRTableCell unitPriceCaption;
        private DevExpress.XtraReports.UI.XRTableCell lineTotalCaption;
        private DevExpress.XtraReports.UI.XRTableRow invoiceNumberCaptionRow;
        private DevExpress.XtraReports.UI.XRTableRow invoiceNumberRow;
        private DevExpress.XtraReports.UI.XRTableCell invoiceNumberCaption;
        private DevExpress.XtraReports.UI.XRTableCell invoiceNumber;
        private DevExpress.XtraReports.UI.XRTable totalTable;
        private DevExpress.XtraReports.UI.XRTableRow subtotalRow;
        private DevExpress.XtraReports.UI.XRTableRow discountRow;
        private DevExpress.XtraReports.UI.XRTableRow taxRow;
        private DevExpress.XtraReports.UI.XRTableRow totalRow;
        private DevExpress.XtraReports.UI.XRTableCell subtotalCaption;
        private DevExpress.XtraReports.UI.XRTableCell subtotal;
        private DevExpress.XtraReports.UI.XRTableCell discountCaption;
        private DevExpress.XtraReports.UI.XRTableCell discount;
        private DevExpress.XtraReports.UI.XRTableCell taxCaption;
        private DevExpress.XtraReports.UI.XRTableCell tax;
        private DevExpress.XtraReports.UI.XRTableCell totalCaption;
        private DevExpress.XtraReports.UI.XRTableCell total;
        private DevExpress.XtraReports.UI.XRControlStyle baseControlStyle;
        private DevExpress.XtraReports.UI.CalculatedField LineTotalCalcField;
        private DevExpress.XtraReports.UI.CalculatedField SubtotalCalcField;
        private DevExpress.XtraReports.UI.CalculatedField TotalCalcField;
        private DevExpress.XtraReports.Parameters.Parameter InvoiceDateParameter;
        private DevExpress.XtraReports.Parameters.Parameter QuantityParameter;
        private DevExpress.XtraReports.Parameters.Parameter UnitPriceParameter;
        private DevExpress.XtraReports.Parameters.Parameter DiscountParameter;
        private DevExpress.XtraReports.Parameters.Parameter TaxParameter;
    }
}
